cache:
  directories:
    - $HOME/.m2
install: true
language: java
jdk:
- oraclejdk8
os:
  - linux
sudo: required
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install python-pip
  - sudo pip install --upgrade boltkit
  - openssl aes-256-cbc -K $encrypted_1ad9bc7ab469_key -iv $encrypted_1ad9bc7ab469_iv -in .travisdeploykey.enc -out .travisdeploykey -d
after_success:
  - git config --global user.email "travis@bsimard.com"
  - git config --global user.name "Travis CI"
  - eval "$(ssh-agent -s)" #start the ssh agent
  - chmod 600 .travis-key
  - ssh-add .travis-key
  - if [[ "$TRAVIS_PULL_REQUEST" = "false"  && "$TRAVIS_BRANCH" == "master" ]]; then mvn clean package site; fi
  - if [[ "$TRAVIS_PULL_REQUEST" = "false"  && "$NEO4J_VERSION" == "2.3.2" && "$TRAVIS_JDK_VERSION" == "openjdk7" &&  "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then mvn clean cobertura:cobertura coveralls:report -Pcoverage -Dcoverall.token=$COVERALL_TOKEN; fi

script: "mvn clean test"
notifications:
  email:
    on_success: never
    on_failure: change