cache:
  directories:
    - $HOME/.m2
install: true
language: java
jdk:
- oraclejdk8
os:
  - linux
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install python-pip
  - pip install --upgrade boltkit

script: "mvn clean test"
notifications:
  email:
    on_success: never
    on_failure: change