= Neo4j Object Query Mapper

== Why this project ?

It's not an OGM (object graph mapper), this project is just a stupid client on top of the neo4j java driver.

* Simple and small Neo4j client
* Singleton for the Neo4j Driver (as needed)
* Simple and single configuration file
* Stupid query object mapping
* Transparent for single or cluster architecture

== Installation

TODO

== Configuration

All the configuration comes from one file : **neo4j-driver.properties**
This should be at the root of the classpath.

[source,properties]
----
# Neo4j driver url
neo4j.url=bolt://localhost

# Neo4j user
neo4j.user=neo4j

# Neo4j password
neo4j.password=admin

# (int) Max number of idle connection into the pool
# neo4j.maxIdleConnectionPoolSize=5

# (long) Threshold of idle time from which we test a connection (in seconds)
# neo4j.idleTimeBeforeConnectionTest=3600

# (boolean) Do we log leaked session ?
# neo4j.logLeakedSessions=true

# (boolean) Traffic encrypted ?
# neo4j.encrypted=true
----

NOTE: To make this configuration dynamic, you can use some maven filters

IMPORTANT: You can override those properties, with a second files named : **neo4j-driver-ext.properties** . This file must be also at the root of the classpath, like into the **shared/classes/** folder of a tomcat server.

== How to use it ?

Just call it like this for a read query

[source,java]
----
import org.neo4j.driver.*
import static org.neo4j.driver.v1.Values.parameters;
...
Neo4jClient.read("MATCH (n:Person { name:$name, born:$born }) RETURN n", parameters( "name", "Keanu Reeves", "born", 1964 ));
----

And for a write query :

[source,java]
----
Neo4jClient.write("CREATE (n:Person { name:$name, born:$born }) RETURN n", parameters( "name", "Keanu Reeves", "born", 1964 ))
----

== Test requirement

This project has a dependency on https://github.com/neo4j-contrib/boltkit[Boltkit] for the test.
So you have to install it before to launch tests.